prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: false
  alertmanager:
    enabled: true
    persistentVolume:
      enabled: false
    service:
      type: NodePort
      nodePort: 30021
    # cluster:
    #   listenAddress:

loki:
  enabled: true
  config:
    ruler:
      enable_api: true
      storage:
        type: local
        local:
          directory: /tmp/loki/rules
      rule_path: /tmp/loki/rules-temp
      alertmanager_url: http://monitoring-prometheus-alertmanager.monitoring
      external_url: http://192.168.110.12:30021
      ring:
        kvstore:
          store: inmemory

promtail:
  enabled: true
  config:
    clients:
      - url: http://monitoring-loki.monitoring:3100/loki/api/v1/push

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30020
  adminUser: admin
  adminPassword: admin1@#$

# kubectl create namespace monitoring
# helm delete monitoring --namespace=monitoring
# helm install --values values.yaml monitoring --namespace=monitoring grafana/loki-stack
# helm upgrade --values values.yaml monitoring --namespace=monitoring grafana/loki-stack