prometheus-postgres-exporter:
  enabled: true
  config:
    datasource:
      host: postgres.postgres
      user: admin
      password: admin1@#$
      port: "5432"
      database: 'postgres'
      sslmode: disable