apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingresse
  namespace: traefik
spec:
  rules:
    - host: traefik.192-168-0-1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  traefik
                port:
                  number: 9000