{
 "title": "APP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cctv_no", "label": "CCTV NO", "query": "0,1,2" }
  ]
 },
 "panels": [
  {
   "title": "DETECTING",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(avg_over_time({app=\"cctv-app\"} | logfmt | cctv = `$cctv_no` | unwrap person [2s]))",
     "legendFormat": "Person"
    },
    {
     "expr": "avg(avg_over_time({app=\"cctv-app\"} | logfmt | cctv = `$cctv_no` | unwrap car [2s]))",
     "legendFormat": "Car"
    },
    {
     "expr": "avg(avg_over_time({app=\"cctv-app\"} | logfmt | cctv = `$cctv_no` | unwrap truck [2s]))",
     "legendFormat": "Truck"
    },
    {
     "expr": "avg(avg_over_time({app=\"cctv-app\"} | logfmt | cctv = `$cctv_no` | unwrap bus [2s]))",
     "legendFormat": "Bus"
    },
    {
     "expr": "avg(avg_over_time({app=\"cctv-app\"} | logfmt | cctv = `$cctv_no` | unwrap bicycle [2s]))",
     "legendFormat": "Bicycle"
    },
    {
     "expr": "avg(avg_over_time({app=\"cctv-app\"} | logfmt | cctv = `$cctv_no` | unwrap motorcycle [2s]))",
     "legendFormat": "Motorcycle"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "timeseries",
   "description": "Percent of time over the past sample period during which one or more kernels was executing on the GPU.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(nvidia_smi_utilization_gpu_ratio[5m])",
     "legendFormat": "GPU Usage"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "timeseries",
   "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(nvidia_smi_memory_used_bytes[5m]) / nvidia_smi_memory_total_bytes",
     "legendFormat": "RAM Usage"
    }
   ]
  }
 ]
}