{
 "title": "TEST",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "graph",
   "description": "Percent of time over the past sample period during which one or more kernels was executing on the GPU.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{uuid=\"b6090e5c-ca26-0942-c3f7-34caaf907b48\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "graph",
   "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_utilization_memory_ratio{uuid=\"b6090e5c-ca26-0942-c3f7-34caaf907b48\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "LOCATION",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{pod=\"test-app-6576975cc7-5wbbc\"} | regexp `gps=(?P<lat>[^,]+),(?P<lng>[^ ]+)` | line_format `lat={{.lat}} lng={{.lng}}` | logfmt",
     "legendFormat": "1st",
     "maxLines": 1
    },
    {
     "expr": "{pod=\"test-app-6576975cc7-cn76r\"} | regexp `gps=(?P<lat>[^,]+),(?P<lng>[^ ]+)` | line_format `lat={{.lat}} lng={{.lng}}` | logfmt",
     "legendFormat": "2nd",
     "maxLines": 1
    },
    {
     "expr": "{pod=\"test-app-6576975cc7-kszqt\"} | regexp `gps=(?P<lat>[^,]+),(?P<lng>[^ ]+)` | line_format `lat={{.lat}} lng={{.lng}}` | logfmt",
     "legendFormat": "3rd",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "DETECTING",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "avg(avg_over_time({app=\"test-app\"} | logfmt | unwrap people [5s]))",
     "legendFormat": "People"
    },
    {
     "expr": "avg(avg_over_time({app=\"test-app\"} | logfmt | unwrap tank [5s]))",
     "legendFormat": "Tank"
    },
    {
     "expr": "avg(avg_over_time({app=\"test-app\"} | logfmt | unwrap fighter [5s]))",
     "legendFormat": "Fighter"
    }
   ]
  }
 ]
}