apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry
  
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-data-pv
  namespace: docker-registry
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /workspace/k8s/docker-registry/registry-data/
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi

---

apiVersion: v1
kind: Service
metadata:
  name: registry-server
  namespace: docker-registry
spec:
  type: NodePort
  selector:
    app: registry-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-server
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-server
  template:
    metadata:
      labels:
        app: registry-server
    spec:
      containers:
        - name: registry-server
          image: registry:2.8.2
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin
              value: "['*']"
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods
              value: "['HEAD','GET','OPTIONS','DELETE']"
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials
              value: "[true]"
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers
              value: "['Authorization,Accept,Cache-Control']"
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers
              value: "['Docker-Content-Digest']"
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          volumeMounts:
            - name: registry-data
              mountPath: /var/lib/registry
      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: registry-data-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: docker-registry
spec:
  type: NodePort
  selector:
    app: registry-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
        - name: registry-ui
          image: joxit/docker-registry-ui:main
          ports:
            - containerPort: 80
          env:
            - name: SINGLE_REGISTRY
              value: "true"
            - name: REGISTRY_TITLE
              value: "Docker Registry UI"
            - name: DELETE_IMAGES
              value: "true"
            - name: SHOW_CONTENT_DIGEST
              value: "true"
            - name: NGINX_PROXY_PASS_URL
              value: "http://registry-server.docker-registry:5000"
            - name: SHOW_CATALOG_NB_TAGS
              value: "true"
            - name: CATALOG_MIN_BRANCHES
              value: "1"
            - name: CATALOG_MAX_BRANCHES
              value: "1"
            - name: TAGLIST_PAGE_SIZE
              value: "100"
            - name: REGISTRY_SECURED
              value: "false"
            - name: CATALOG_ELEMENTS_LIMIT
              value: "1000"