FROM nvidia/cuda:11.6.1-cudnn8-devel-ubuntu20.04
ARG DEBIAN_FRONTEND=noninteractive
ENV PATH /usr/local/bin:$PATH
ENV LANG C.UTF-8
ENV TZ Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install -y python3 python3-pip libgl1-mesa-glx libglib2.0-0 tzdata
RUN pip install --upgrade pip
RUN pip install ultralytics
COPY ./ ./app