#set deployment yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cctv-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cctv-app
  template:
    metadata:
      labels:
        app: cctv-app
    spec:
      containers:
      - name: cctv-app
        image: 192.168.2.100:30011/cctv-app:0.1
        command: ["/bin/python3","/app/cctv_detect.py"]
        ports:
        - containerPort: 80
        resources:
          limits:
            nvidia.com/gpu: 1