apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-conf-pv
spec:
  capacity:
    storage: 32Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /workspace/k8s/nginx/conf/nginx.conf
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-conf-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi