sudo rm -rf ~/.kube/config
sudo rm -rf /var/run/calico/ 
sudo rm -rf /var/lib/calico/ 
sudo rm -rf /var/lib/cni/ 
sudo rm -rf /root/.kube/ 
sudo rm -rf ~/.kube/ 
sudo rm -rf /var/lib/etcd/
sudo rm -rf /run/flannel
sudo rm -rf /etc/cni
