apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/name: nvidia-gpu-exporter
    release: prometheus-stack
  name: nvidia-exporter-nvidia-gpu-exporter
  namespace: monitoring
spec:
  endpoints:
  - port: http
    scheme: http
  jobLabel: jobLabel
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-stack
      app.kubernetes.io/name: nvidia-gpu-exporter